Small updates to compile

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -1,7 +1,8 @@
-#!/usr/bin/env bash
+#!/bin/bash
 # bin/compile <build-dir> <cache-dir> <env-dir>
 
-set -x
+# fail fast
+set -e
 
 header() {
   echo "" || true
